#!/usr/bin/env python3
"""Assemble ordered OctoScript sources for the host's single Splash entry."""
import argparse
import json
from pathlib import Path
from urllib.parse import urlsplit

ROOT = Path(__file__).resolve().parents[1]
ORDER = [
    'src/app/config.splash',
    'src/contracts/news.splash',
    'src/data/ingestion/sources.json',
    'src/data/ingestion/normalize.splash',
    'src/data/storage/records.splash',
    'src/data/retrieval/interests.splash',
    'src/data/ingestion/http.splash',
    'src/data/ingestion/feeds.splash',
    'src/agent/runtime/connectivity.splash',
    'src/app/controller.splash',
    'src/frontend/styles.splash',
    'src/frontend/components/news_list.splash',
    'src/frontend/pages/feed.splash',
    'src/frontend/pages/tracking.splash',
    'src/frontend/pages/bookmarks.splash',
    'src/frontend/pages/schedule.splash',
    'src/frontend/pages/detail.splash',
    'src/frontend/pages/settings.splash',
    'src/frontend/app_view.splash',
    'src/app/startup.splash',
]


def source_catalog(root=ROOT):
    catalog = json.loads((root / 'src/data/ingestion/sources.json').read_text(encoding='utf-8'))
    ids = set()
    for source in catalog['sources']:
        if source['id'] in ids:
            raise ValueError(f"Duplicate source: {source['id']}")
        ids.add(source['id'])
        url = urlsplit(source['url'])
        if url.scheme != 'https' or not url.hostname or url.username or url.password:
            raise ValueError(f"Invalid source URL: {source['id']}")
        if source['kind'] not in {'rss', 'google', 'digest', 'hn'}:
            raise ValueError(f"Unsupported source kind: {source['id']}")
    return catalog


def catalog_script(catalog):
    def value(v):
        return json.dumps(v, ensure_ascii=False)
    rows = ['    {' + ' '.join(f'{key}: {value(v)}' for key, v in source.items()) + '}'
            for source in catalog['sources']]
    hosts = sorted({urlsplit(source['url']).hostname for source in catalog['sources']}
                   | set(catalog.get('redirect_hosts', [])))
    return 'let news_sources = [\n' + '\n'.join(rows) + '\n]\nlet news_hosts = ' + value(hosts) + '\n'


def assemble(root=ROOT, paths=None):
    chunks = ['// GENERATED by scripts/assemble.py; edit src/, never this file.\n'
              '// Derived UI/runtime: OctoSense News; Apache-2.0, see LICENSE and NOTICE.\n']
    spans = []
    next_line = 3
    for relative in paths or ORDER:
        content = (catalog_script(source_catalog(root)) if relative.endswith('.json') else
                   (root / relative).read_text(encoding='utf-8').replace('\r\n', '\n'))
        chunk = f'\n// BEGIN {relative}\n{content.rstrip()}\n// END {relative}\n'
        spans.append({'source': relative, 'generated_start': next_line + 2,
                      'generated_end': next_line + 1 + len(content.rstrip().splitlines()),
                      'source_start': 1, 'generated_catalog': relative.endswith('.json')})
        next_line += chunk.count('\n')
        chunks.append(chunk)
    return ''.join(chunks), spans


def build(root=ROOT, check=False):
    output, spans = assemble(root)
    target = root / 'bundle/main.splash'
    if check:
        if not target.exists() or target.read_text(encoding='utf-8').replace('\r\n', '\n') != output:
            raise SystemExit('bundle/main.splash is stale; run python scripts/assemble.py')
        return
    target.write_text(output, encoding='utf-8', newline='\n')
    (root / 'build').mkdir(exist_ok=True)
    (root / 'build/source-map.json').write_text(json.dumps(spans, indent=2), encoding='utf-8')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    build(check=args.check)
    print('Source assembly checked' if args.check else 'Assembled bundle/main.splash')
