[package]
name = "cfaw-windows-webreader"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
webview2-com = "=0.39.1"
url = "2"
windows = { version = "=0.62.2", features = ["Win32_Foundation", "Win32_System_Com", "Win32_System_Com_StructuredStorage", "Win32_System_Memory", "Win32_UI_WindowsAndMessaging"] }

[dev-dependencies]
windows = { version = "=0.62.2", features = ["Win32_Graphics_Gdi"] }
